# Generated by Django 4.0.3 on 2022-03-22 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=7)),
                ('question', models.CharField(max_length=42, unique=True)),
                ('solution', models.CharField(max_length=42, unique=True)),
                ('average_completion_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=14, editable=False, max_digits=24)),
                ('latitude', models.DecimalField(decimal_places=14, editable=False, max_digits=24)),
                ('allowable_distance_difference', models.DecimalField(decimal_places=14, default=0.0006, max_digits=24)),
                ('average_game_completion_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_address', models.CharField(max_length=42, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('last_login_time', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 13, 33, 56, 382243))),
                ('challenge_id_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_five', to='play.challenges')),
                ('challenge_id_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_four', to='play.challenges')),
                ('challenge_id_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_one', to='play.challenges')),
                ('challenge_id_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_seven', to='play.challenges')),
                ('challenge_id_six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_six', to='play.challenges')),
                ('challenge_id_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_three', to='play.challenges')),
                ('challenge_id_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_two', to='play.challenges')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Landmarks',
            fields=[
                ('landmark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('landmark_name', models.CharField(max_length=42, unique=True)),
                ('longitude', models.DecimalField(decimal_places=14, editable=False, max_digits=24)),
                ('latitude', models.DecimalField(decimal_places=14, editable=False, max_digits=24)),
                ('average_challenge_completion_time', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.cities')),
            ],
        ),
        migrations.AddField(
            model_name='challenges',
            name='landmark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.landmarks'),
        ),
    ]
