# Generated by Django 4.0.3 on 2022-03-23 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='landmark_id',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='landmarks',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_five',
            new_name='challenge_five',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_four',
            new_name='challenge_four',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_one',
            new_name='challenge_one',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_seven',
            new_name='challenge_seven',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_six',
            new_name='challenge_six',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_three',
            new_name='challenge_three',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='challenge_id_two',
            new_name='challenge_two',
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 19, 27, 51, 524369)),
        ),
    ]
