# Generated by Django 4.0.3 on 2022-03-23 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_alter_challenges_challenge_id_alter_cities_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge_id',
            field=models.UUIDField(default=uuid.UUID('510d95f7-f450-41d4-b230-0eb1934195c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.UUIDField(default=uuid.UUID('9c0b06a5-387d-45b8-9394-e6a86efb3c3e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='landmark_id',
            field=models.UUIDField(default=uuid.UUID('6a647428-8a42-4c85-a6b1-a9646ee38f04'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
