# Generated by Django 4.0.3 on 2022-03-23 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_alter_challenges_challenge_id_alter_cities_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge_id',
            field=models.UUIDField(default=uuid.UUID('d8564ad5-512e-45ed-b9b7-298a4e630703'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.UUIDField(default=uuid.UUID('c5de9e85-19d7-489f-a766-ba7820d86a6d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='landmark_id',
            field=models.UUIDField(default=uuid.UUID('7bf8a21e-2b0c-4f26-ba51-d752481438ef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_address', models.CharField(max_length=42, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('last_login_time', models.DateTimeField(default=datetime.datetime(2022, 3, 23, 14, 22, 9, 437337))),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.cities')),
            ],
        ),
    ]
