# Generated by Django 4.0.3 on 2022-03-23 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0031_alter_cities_city_id_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 15, 0, 27, 652761)),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
