# Generated by Django 4.0.3 on 2022-03-23 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0035_alter_users_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
