# Generated by Django 4.0.3 on 2022-03-23 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0036_alter_users_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
