# Generated by Django 4.0.3 on 2022-03-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0039_alter_landmarks_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarks',
            name='question',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
