# Generated by Django 4.0.3 on 2022-03-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0040_alter_landmarks_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='completed_challenge_count',
            field=models.IntegerField(default=0),
        ),
    ]
