# Generated by Django 4.0.3 on 2022-03-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0041_users_completed_challenge_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmarks',
            old_name='average_challenge_completion_time',
            new_name='total_challenge_completion_time',
        ),
    ]
