# Generated by Django 4.0.3 on 2022-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0042_rename_average_challenge_completion_time_landmarks_total_challenge_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarks',
            name='total_challenge_completions',
            field=models.DecimalField(decimal_places=14, default=1.0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='total_challenge_completion_time',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=24),
        ),
    ]
