# Generated by Django 4.0.3 on 2022-03-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0043_landmarks_total_challenge_completions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarks',
            name='total_challenge_completions',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=24),
        ),
    ]
