# Generated by Django 4.0.3 on 2022-03-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0044_alter_landmarks_total_challenge_completions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarks',
            name='total_challenge_completions',
            field=models.IntegerField(default=0),
        ),
    ]
