# Generated by Django 4.0.3 on 2022-03-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0046_users_landmark_five_users_landmark_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarks',
            name='average_challenge_completion_time',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=24),
        ),
    ]
