# Generated by Django 4.0.3 on 2022-03-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0047_landmarks_average_challenge_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active_game_time',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=24),
        ),
    ]
