# Generated by Django 4.0.3 on 2022-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0049_cities_total_game_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='average_game_completion_time',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=24),
        ),
    ]
