# Generated by Django 4.0.3 on 2022-03-26 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0051_remove_cities_total_game_completion_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecords',
            name='id',
        ),
        migrations.AddField(
            model_name='timerecords',
            name='time_record_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
