# Generated by Django 4.0.3 on 2022-03-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0052_remove_timerecords_id_timerecords_time_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecords',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='play.cities'),
        ),
        migrations.AlterField(
            model_name='timerecords',
            name='landmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='play.landmarks'),
        ),
    ]
