# Generated by Django 4.0.3 on 2022-03-26 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0055_timerecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecords',
            name='completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
