# Generated by Django 4.0.3 on 2022-03-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0057_landmarks_hint_alter_landmarks_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
    ]
