# Generated by Django 4.0.3 on 2022-03-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0057_landmarks_hint_alter_landmarks_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecords',
            name='time_record_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
