# Generated by Django 4.0.3 on 2022-03-29 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0058_alter_timerecords_time_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecords',
            name='time_record_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
