# Generated by Django 4.0 on 2022-04-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0059_alter_timerecords_time_record_id'),
        ('play', '0059_users_user_name'),
    ]

    operations = [
    ]
