# Generated by Django 4.0 on 2022-04-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0060_merge_20220401_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='landmark_five',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_five', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='landmark_four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_four', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='landmark_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_one', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='landmark_seven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_seven', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='landmark_six',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_six', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='landmark_three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_three', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='landmark_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_two', to='play.landmarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
