# Generated by Django 4.0.3 on 2022-06-05 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0061_alter_users_landmark_five_alter_users_landmark_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChattanoogaLandmarkTimeRecords',
            fields=[
                ('time_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ice_cream_show', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('old_building_collapse', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('river_street_deli', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('clumpies', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('coolidge_park', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('renaissance_park', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('hunter_art_museum', models.DecimalField(decimal_places=14, default=0.0, max_digits=24)),
                ('starting_landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark_one', to='play.landmarks')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_five',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_four',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_one',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_seven',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_six',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_three',
        ),
        migrations.RemoveField(
            model_name='users',
            name='landmark_two',
        ),
        migrations.DeleteModel(
            name='TimeRecords',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
