# Generated by Django 4.0.3 on 2022-06-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0064_remove_cities_allowable_distance_difference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattanoogalandmarktimerecords',
            name='starting_landmark',
        ),
    ]
