# Generated by Django 4.0.3 on 2022-06-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0065_remove_chattanoogalandmarktimerecords_starting_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattanoogalandmarktimerecords',
            name='starting_landmark',
            field=models.ForeignKey(default='16c6b0d7-d473-4790-a6b6-a67b8036c5a4', on_delete=django.db.models.deletion.CASCADE, related_name='landmark_one', to='play.landmarks'),
            preserve_default=False,
        ),
    ]
