# Generated by Django 4.0.3 on 2022-06-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0066_chattanoogalandmarktimerecords_starting_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattanoogalandmarktimerecords',
            name='game_start',
        ),
    ]
