"""
Django settings for gameapp project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Gather environment variables for database connection.
ENV_VARS = []
if 'RDS_DB_NAME' in os.environ:
    ENV_VARS[0] = os.environ['SECRET_KEY']
    ENV_VARS[1] = os.environ['RDS_DB_NAME']
    ENV_VARS[2] = os.environ['RDS_USERNAME']
    ENV_VARS[3] = os.environ['RDS_PASSWORD']
    ENV_VARS[4] = os.environ['RDS_HOSTNAME']
    ENV_VARS[5] = os.environ['RDS_PORT']
    ENV_VARS[6] = os.environ['REDIS_PORT']
else:
    ENV_FILE = Path('C:/Users/Rudy451/codeworks/pair-programming/AllForOne/.env').absolute()
    with open(ENV_FILE) as env_f:
        ENV_VARS += [line.strip("\n").split("=")[1] for line in env_f]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV_VARS[0]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1', ENV_VARS[4], '*']
#ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['allforone-django-env.eba-n62efk9w.us-west-2.elasticbeanstalk.com', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'corsheaders',
    'play',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gameapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gameapp.wsgi.application'

# Cache
CACHE_TTL = 60 * 60 * 4

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://" + ENV_VARS[4] + ":" + ENV_VARS[6] + "/0",
        "OPTIONS": {
            "CLIENT_CLASS:": "django_redis.client.DefaultClient"
        },
        "TIMEOUT": CACHE_TTL
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': ENV_VARS[1],
        'USER': ENV_VARS[2],
        'PASSWORD': ENV_VARS[3],
        'HOST': ENV_VARS[4],
        'PORT': ENV_VARS[5]
    }
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## Cross-Origin Resource Sharing Settings ##
CORS_ORIGIN_ALLOW_ALL=True
